PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pi: <https://process.intelligence/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# SELECT next workflow activities authorized by ALIVE_CLAIM checkpoints
SELECT ?checkpoint ?authorizedDownstream ?label
WHERE {
  ?checkpoint a pi:ALIVE_CLAIM ;
              pi:authorizedDownstream ?authorizedDownstream .
  ?authorizedDownstream rdfs:label ?label .
}
ORDER BY ?checkpoint
